### ISSUE TITLE
ComfyUI-IF_AI_HFDownloaderNode\requirements.txt (line 2)) (1.0.1)

### ISSUE THREAD

**Issue by 0m0Ding** [if-ai/ComfyUI-IF_AI_HFDownloaderNode#1]
Requirement already satisfied: python-dotenv in d:\ai\sd\comfyui-aki-v1.3\python\lib\site-packages (from -r D:\AI\SD\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_AI_HFDownloaderNode\requirements.txt (line 2)) (1.0.1)
ERROR: Could not find a version that satisfies the requirement tqm (from versions: none)
ERROR: No matching distribution found for tqm

when it install,I close the internet,it make me get the worse,like this, I open this requirements.txt ,and it show 'python-dotenv'.
so I think it's problem is I can't installed the python--python-dotenv.but I don't how to do that ,who can tell me ,pls.
![Uploading 2024-07-18-211529.jpg…]()

**Comment by if-ai** [comment]
Sorry try downloading again I made a mistake is tqdm not tqm

**Comment by 0m0Ding** [comment]
> Sorry try downloading again I made a mistake is tqdm not tqm

OK,I'll try.  thanks for give me answer
